# Generated by Django 6.0.1 on 2026-02-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('EC', 'EC'), ('ME', 'ME')], max_length=5)),
                ('sem', models.PositiveSmallIntegerField(default=1)),
                ('sec', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('class_section', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('is_present', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_app.student')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
                'unique_together': {('student', 'date', 'subject', 'class_section')},
            },
        ),
    ]
