# Generated by Django 6.0.1 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gmail",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
